# Tugas 7 (Credit Risk)

In [32]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from collections import OrderedDict
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [33]:
dataset = "https://raw.githubusercontent.com/wahyuarilsaputra/dataset/main/credit_score.csv"
data = pd.read_csv(dataset)

In [34]:
data.head()
data1 = data.drop(columns=['kpr_aktif', 'rata_rata_overdue'])

Data1 = Data tanpa kpr_aktif dan rata rata overdue

In [35]:
data2 = data[["kpr_aktif"]]

data2 = data Kpr_Aktif

In [36]:
data2.head(25)

kpr_aktif
0         YA
1         YA
2      TIDAK
3         YA
4      TIDAK
5      TIDAK
6      TIDAK
7      TIDAK
8      TIDAK
9      TIDAK
10     TIDAK
11     TIDAK
12     TIDAK
13     TIDAK
14     TIDAK
15     TIDAK
16        YA
17     TIDAK
18     TIDAK
19     TIDAK
20     TIDAK
21     TIDAK
22     TIDAK
23     TIDAK
24     TIDAK

Merubah String data menjadi numerik

In [37]:
datakpr = pd.get_dummies(data2)
datakpr

kpr_aktif_TIDAK  kpr_aktif_YA
0                  0             1
1                  0             1
2                  1             0
3                  0             1
4                  1             0
..               ...           ...
895                0             1
896                0             1
897                1             0
898                1             0
899                1             0

[900 rows x 2 columns]

datakpr = data kpr yang sudah diubah menjadi angka

In [38]:
data3 = data[["rata_rata_overdue"]]

data3 = data rata-rata_overdue

In [39]:
data3.head(25)

rata_rata_overdue
0       61 - 90 days
1       61 - 90 days
2        0 - 30 days
3       46 - 60 days
4       31 - 45 days
5        0 - 30 days
6       31 - 45 days
7       31 - 45 days
8       31 - 45 days
9       31 - 45 days
10      31 - 45 days
11      31 - 45 days
12      31 - 45 days
13      31 - 45 days
14      31 - 45 days
15      31 - 45 days
16       0 - 30 days
17       0 - 30 days
18       0 - 30 days
19      31 - 45 days
20      31 - 45 days
21      31 - 45 days
22       0 - 30 days
23       0 - 30 days
24       0 - 30 days

In [40]:
datarata = pd.get_dummies(data3)

In [41]:
datarata

rata_rata_overdue_0 - 30 days  rata_rata_overdue_31 - 45 days  \
0                                0                               0   
1                                0                               0   
2                                1                               0   
3                                0                               0   
4                                0                               1   
..                             ...                             ...   
895                              0                               0   
896                              0                               0   
897                              1                               0   
898                              0                               1   
899                              1                               0   

     rata_rata_overdue_46 - 60 days  rata_rata_overdue_61 - 90 days  \
0                                 0                               1   
1                                 0                               1   
2                                 0                               0   
3                                 1                               0   
4                                 0                               0   
..                              ...                             ...   
895                               0                               0   
896                               1                               0   
897                               0                               0   
898                               0                               0   
899                               0                               0   

     rata_rata_overdue_> 90 days  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  
..                           ...  
895                            1  
896                            0  
897                            0  
898                            0  
899                            0  

[900 rows x 5 columns]

In [42]:
datanumeric = pd.concat([datakpr, datarata], axis=1)

In [43]:
Hasil = pd.concat([data1, datanumeric], axis=1)
Hasil

Unnamed: 0 kode_kontrak  pendapatan_setahun_juta  durasi_pinjaman_bulan  \
0             1   AGR-000001                      295                     48   
1             2   AGR-000011                      271                     36   
2             3   AGR-000030                      159                     12   
3             4   AGR-000043                      210                     12   
4             5   AGR-000049                      165                     36   
..          ...          ...                      ...                    ...   
895         896   AGR-010739                      112                     48   
896         897   AGR-010744                      120                     48   
897         898   AGR-010758                      166                     24   
898         899   AGR-010775                      196                     48   
899         900   AGR-010790                      204                     24   

     jumlah_tanggungan  risk_rating  kpr_aktif_TIDAK  kpr_aktif_YA  \
0                    5            4                0             1   
1                    5            4                0             1   
2                    0            1                1             0   
3                    3            3                0             1   
4                    0            2                1             0   
..                 ...          ...              ...           ...   
895                  5            5                0             1   
896                  2            3                0             1   
897                  2            1                1             0   
898                  0            2                1             0   
899                  2            1                1             0   

     rata_rata_overdue_0 - 30 days  rata_rata_overdue_31 - 45 days  \
0                                0                               0   
1                                0                               0   
2                                1                               0   
3                                0                               0   
4                                0                               1   
..                             ...                             ...   
895                              0                               0   
896                              0                               0   
897                              1                               0   
898                              0                               1   
899                              1                               0   

     rata_rata_overdue_46 - 60 days  rata_rata_overdue_61 - 90 days  \
0                                 0                               1   
1                                 0                               1   
2                                 0                               0   
3                                 1                               0   
4                                 0                               0   
..                              ...                             ...   
895                               0                               0   
896                               1                               0   
897                               0                               0   
898                               0                               0   
899                               0                               0   

     rata_rata_overdue_> 90 days  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  
..                           ...  
895                            1  
896                            0  
897                            0  
898                            0  
899                            0  

[900 rows x 13 columns]

Min Max Normalisasi

In [44]:
dataNormalisasi = ['pendapatan_setahun_juta', 'durasi_pinjaman_bulan', 'jumlah_tanggungan']
FrameNormalisasi = Hasil[dataNormalisasi]
FrameNormalisasi

pendapatan_setahun_juta  durasi_pinjaman_bulan  jumlah_tanggungan
0                        295                     48                  5
1                        271                     36                  5
2                        159                     12                  0
3                        210                     12                  3
4                        165                     36                  0
..                       ...                    ...                ...
895                      112                     48                  5
896                      120                     48                  2
897                      166                     24                  2
898                      196                     48                  0
899                      204                     24                  2

[900 rows x 3 columns]

In [45]:
scaler = MinMaxScaler()

In [46]:
scaler.fit(FrameNormalisasi)

MinMaxScaler()

In [47]:
hasilNormalisasi = scaler.transform(FrameNormalisasi)

In [48]:
hasilNormalisasi = pd.DataFrame(hasilNormalisasi,columns = dataNormalisasi)
hasilNormalisasi

pendapatan_setahun_juta  durasi_pinjaman_bulan  jumlah_tanggungan
0                   0.978261               1.000000           0.833333
1                   0.873913               0.666667           0.833333
2                   0.386957               0.000000           0.000000
3                   0.608696               0.000000           0.500000
4                   0.413043               0.666667           0.000000
..                       ...                    ...                ...
895                 0.182609               1.000000           0.833333
896                 0.217391               1.000000           0.333333
897                 0.417391               0.333333           0.333333
898                 0.547826               1.000000           0.000000
899                 0.582609               0.333333           0.333333

[900 rows x 3 columns]

In [49]:
Hasil = pd.concat([Hasil, hasilNormalisasi], axis=1)
Hasil

Unnamed: 0 kode_kontrak  pendapatan_setahun_juta  durasi_pinjaman_bulan  \
0             1   AGR-000001                      295                     48   
1             2   AGR-000011                      271                     36   
2             3   AGR-000030                      159                     12   
3             4   AGR-000043                      210                     12   
4             5   AGR-000049                      165                     36   
..          ...          ...                      ...                    ...   
895         896   AGR-010739                      112                     48   
896         897   AGR-010744                      120                     48   
897         898   AGR-010758                      166                     24   
898         899   AGR-010775                      196                     48   
899         900   AGR-010790                      204                     24   

     jumlah_tanggungan  risk_rating  kpr_aktif_TIDAK  kpr_aktif_YA  \
0                    5            4                0             1   
1                    5            4                0             1   
2                    0            1                1             0   
3                    3            3                0             1   
4                    0            2                1             0   
..                 ...          ...              ...           ...   
895                  5            5                0             1   
896                  2            3                0             1   
897                  2            1                1             0   
898                  0            2                1             0   
899                  2            1                1             0   

     rata_rata_overdue_0 - 30 days  rata_rata_overdue_31 - 45 days  \
0                                0                               0   
1                                0                               0   
2                                1                               0   
3                                0                               0   
4                                0                               1   
..                             ...                             ...   
895                              0                               0   
896                              0                               0   
897                              1                               0   
898                              0                               1   
899                              1                               0   

     rata_rata_overdue_46 - 60 days  rata_rata_overdue_61 - 90 days  \
0                                 0                               1   
1                                 0                               1   
2                                 0                               0   
3                                 1                               0   
4                                 0                               0   
..                              ...                             ...   
895                               0                               0   
896                               1                               0   
897                               0                               0   
898                               0                               0   
899                               0                               0   

     rata_rata_overdue_> 90 days  pendapatan_setahun_juta  \
0                              0                 0.978261   
1                              0                 0.873913   
2                              0                 0.386957   
3                              0                 0.608696   
4                              0                 0.413043   
..                           ...                      ...   
895                            1                 0.182609   
896                  

In [50]:
label = ['Unnamed: 0','kode_kontrak']
Hasil = Hasil.drop(columns = label)
Hasil

pendapatan_setahun_juta  durasi_pinjaman_bulan  jumlah_tanggungan  \
0                        295                     48                  5   
1                        271                     36                  5   
2                        159                     12                  0   
3                        210                     12                  3   
4                        165                     36                  0   
..                       ...                    ...                ...   
895                      112                     48                  5   
896                      120                     48                  2   
897                      166                     24                  2   
898                      196                     48                  0   
899                      204                     24                  2   

     risk_rating  kpr_aktif_TIDAK  kpr_aktif_YA  \
0              4                0             1   
1              4                0             1   
2              1                1             0   
3              3                0             1   
4              2                1             0   
..           ...              ...           ...   
895            5                0             1   
896            3                0             1   
897            1                1             0   
898            2                1             0   
899            1                1             0   

     rata_rata_overdue_0 - 30 days  rata_rata_overdue_31 - 45 days  \
0                                0                               0   
1                                0                               0   
2                                1                               0   
3                                0                               0   
4                                0                               1   
..                             ...                             ...   
895                              0                               0   
896                              0                               0   
897                              1                               0   
898                              0                               1   
899                              1                               0   

     rata_rata_overdue_46 - 60 days  rata_rata_overdue_61 - 90 days  \
0                                 0                               1   
1                                 0                               1   
2                                 0                               0   
3                                 1                               0   
4                                 0                               0   
..                              ...                             ...   
895                               0                               0   
896                               1                               0   
897                               0                               0   
898                               0                               0   
899                               0                               0   

     rata_rata_overdue_> 90 days  pendapatan_setahun_juta  \
0                              0                 0.978261   
1                              0                 0.873913   
2                              0                 0.386957   
3                              0                 0.608696   
4                              0                 0.413043   
..                           ...                      ...   
895                            1                 0.182609   
896                            0                 0.217391   
897                            0                 0.417391   
898                            0                 0.547826   
899                            0                 0.582609   

     durasi_pinjaman_bulan  jumlah_tanggungan  
0                 1.000000  

In [51]:
percent_amount_of_test_data = 0.3

Menghitung Data
```
# data latih (nilai data)
X_train 

# data tes (nilai data)
X_test 

# data latih (kelas data)
y_train

# data tes (kelas data)
y_test
```

In [52]:
matrices_X = Hasil.iloc[:,1:11].values
matrices_Y = Hasil.iloc[:,0].values

In [53]:
X1 = Hasil.iloc[:,1:11].values
Y1 = Hasil.iloc[:, 0].values

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X1, Y1, test_size = percent_amount_of_test_data, random_state=0)

In [55]:
X1

array([[48,  5,  4, ...,  0,  1,  0],
       [36,  5,  4, ...,  0,  1,  0],
       [12,  0,  1, ...,  0,  0,  0],
       ...,
       [24,  2,  1, ...,  0,  0,  0],
       [48,  0,  2, ...,  0,  0,  0],
       [24,  2,  1, ...,  0,  0,  0]])

In [56]:
Y1

array([295, 271, 159, 210, 165, 220,  70,  88, 163, 100, 166, 163, 162,
       198, 116,  90, 167, 208, 121, 162, 166,  84, 156, 184, 166, 117,
       140, 103,  90, 144, 178, 129, 166, 151, 174, 111, 123, 155, 193,
       189,  98, 204, 174,  78,  91, 104, 178, 152, 166, 197, 157, 171,
       186, 104, 221,  79, 162, 162, 152, 103, 122, 156, 176,  91, 137,
        95, 137, 120, 229,  94, 104, 218, 155, 213, 140, 182, 192, 143,
       193, 190,  93, 128,  81, 179, 191,  87, 100, 115, 192,  83, 190,
       153, 187, 220, 208, 195, 104, 118, 177, 175,  84, 113, 134,  94,
       138, 191, 230, 210, 114, 169, 120, 203, 135, 120, 101, 103, 213,
       109, 146, 220, 201, 128, 177, 167, 172, 178, 146, 157, 152, 270,
       178, 159, 117, 151, 188, 140, 192, 132, 181,  83, 170, 215,  95,
        83, 194,  95, 196,  87, 172,  96, 198, 121, 102, 247, 202, 251,
       215,  81, 176,  84, 169,  95, 115, 145, 195, 203, 205,  75, 225,
       155, 121, 143, 218, 110, 278, 264, 158, 206, 110, 164, 14

In [57]:
### Dictionary to store model and its accuracy

model_accuracy = OrderedDict()

### Dictionary to store model and its precision

model_precision = OrderedDict()

### Dictionary to store model and its recall

model_recall = OrderedDict()

Contoh terdapat Customer dengan nama "Putra"


---


*    overdue 0 - 30  days : 0
*    overdue 31 - 45 days : 1
*    overdue 46 - 60 days : 0 
*    overdue 61 - 90 days : 0
*    overdue > 90 days    : 0 
*    KPR_TIDAK : 0
*    KPR_YA	: 1
*    pendapatan_setahun_juta : 0.582609 
*    durasi_pinjaman_bulan	: 0.666667  
*    jumlah_tanggungan	: 0

Mencari risk Rating berdasarkan isi diatas

```
# Contoh Data Customer 'Putra'
[0,	1,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]
```



Naive Bayes

In [58]:
naive_bayes_classifier = GaussianNB()
naive_bayes_classifier.fit(X_train, y_train)
Y_pred_nb = naive_bayes_classifier.predict(X_test)

cm = confusion_matrix(y_test, Y_pred_nb)

print('Confusion matrix for Gaussian Naive Bayes\n',cm)

naive_bayes_accuracy = round(100 * accuracy_score(y_test, Y_pred_nb), 2)
model_accuracy['Gaussian Naive Bayes'] = naive_bayes_accuracy

naive_bayes_precision = round(100 * precision_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_precision['Gaussian Naive Bayes'] = naive_bayes_precision

naive_bayes_recall = round(100 * recall_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_recall['Gaussian Naive Bayes'] = naive_bayes_recall

print('The accuracy of this model is {} %.'.format(naive_bayes_accuracy))
print('The precision of this model is {} %.'.format(naive_bayes_precision))
print('The recall of this model is {} %.'.format(naive_bayes_recall))

Confusion matrix for Gaussian Naive Bayes
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
The accuracy of this model is 0.74 %.
The precision of this model is 0.12 %.
The recall of this model is 0.74 %.


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [59]:
Y_pred_nb

array([ 86,  96, 147, 144, 235, 259, 213, 147, 183, 231, 213,  93, 161,
        86,  72, 212, 213,  79, 106, 251, 123, 106, 183, 213, 101,  84,
        79, 216, 106,  79,  86, 147, 101, 147, 131, 253, 235, 255, 291,
       123, 235, 213,  96, 127, 101, 106, 181, 144, 213, 131, 123, 101,
       213, 213,  93, 236, 213, 147, 147, 147, 251,  86, 106, 101, 160,
       147, 216, 212, 259, 213,  87, 293,  93, 213, 213, 257,  79, 147,
       106, 231, 213,  93,  79, 123, 253, 183, 213,  79, 123, 213,  93,
       147, 123, 123, 147, 213,  97, 231, 231, 213, 215, 213,  74, 213,
       236, 293, 147, 161, 123, 123,  74, 147, 215, 213, 123, 213, 235,
       235,  93,  86, 181, 255, 106, 131, 251, 213,  82, 213, 213, 231,
       213, 131, 213,  82, 147, 127, 161,  82, 213, 251, 147, 236, 147,
       231, 144,  74, 213,  93,  97, 106, 147, 216, 212, 235, 161,  82,
       183, 291, 212, 213, 123, 213, 213, 131,  93, 213,  74, 213, 253,
        93, 213, 213, 259, 127, 144, 213,  96, 213,  79,  74, 18

In [60]:
clf = GaussianNB()
clf.fit(matrices_X, matrices_Y)
clf_pf = GaussianNB()
clf_pf.partial_fit(matrices_X, matrices_Y, np.unique(matrices_Y))

GaussianNB()

In [61]:
FIRST_IDX = 0

In [62]:
# try with value [0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]
result_test_naive_bayes = clf_pf.predict([[0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]])[FIRST_IDX]
print(f"Customer : Putra Memiliki risk rating {result_test_naive_bayes} Pada metode Gaussian Naive Bayes model")

Customer : Putra Memiliki risk rating 109 Pada metode Gaussian Naive Bayes model


K - Nearest Neighbors


*   Tentukan nilai K = 10 (10 tetangga terdekat)
*   Buat data latih

In [63]:
K = 10
knn = KNeighborsClassifier(n_neighbors = K)

knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [64]:
Y_pred_knn = knn.predict(X_test)

In [65]:
knn.score(X_test, y_test)

0.003703703703703704

In [66]:
# Custom value to predict
result_test_knn = knn.predict([[0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]])
print(f"Customer : Putra Memiliki risk rating {result_test_knn[FIRST_IDX]} Pada metode KNN model")

Customer : Putra Memiliki risk rating 94 Pada metode KNN model


In [67]:
### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_knn)

### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for K - Nearest Neighbors\n',cm)
nn1_accuracy = round(100 * accuracy_score(y_test, Y_pred_knn), 2)
model_accuracy['1 - Nearest Neighbors'] = nn1_accuracy

nn1_precision = round(100 * precision_score(y_test, Y_pred_knn, average = 'weighted'), 2)
model_precision['1 - Nearest Neighbors'] = nn1_precision

nn1_recall = round(100 * recall_score(y_test, Y_pred_knn, average = 'weighted'), 2)
model_recall['1 - Nearest Neighbors'] = nn1_recall

print('The accuracy of this model is {} %.'.format(nn1_accuracy))
print('The precision of this model is {} %.'.format(nn1_precision))
print('The recall of this model is {} %.'.format(nn1_recall))

Confusion matrix for K - Nearest Neighbors
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
The accuracy of this model is 0.37 %.
The precision of this model is 0.05 %.
The recall of this model is 0.37 %.


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Decision Tree

In [68]:
### Applying Decision Tree Classification model

decision_tree_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 27)
decision_tree_classifier.fit(X_train, y_train)


### Predicting the Test set results

Y_pred_dc = decision_tree_classifier.predict(X_test)

In [69]:
### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_dc)

### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for Decision Tree\n',cm)

decision_tree_accuracy = round(100 * accuracy_score(y_test, Y_pred_dc), 2)
model_accuracy['Decision Tree'] = decision_tree_accuracy

decision_tree_precision = round(100 * precision_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_precision['Decision Tree'] = decision_tree_precision

decision_tree_recall = round(100 * recall_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_recall['Decision Tree'] = decision_tree_recall

print('The accuracy of this model is {} %.'.format(decision_tree_accuracy))
print('The precision of this model is {} %.'.format(decision_tree_precision))
print('The recall of this model is {} %.'.format(decision_tree_recall))

Confusion matrix for Decision Tree
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
The accuracy of this model is 0.0 %.
The precision of this model is 0.0 %.
The recall of this model is 0.0 %.


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [70]:
# Custom value to predict
result_test_knn = decision_tree_classifier.predict([[0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]])
print(f"Customer : Putra Memiliki risk rating {result_test_knn[FIRST_IDX]} Pada metode Decision Tree model")

Customer : Putra Memiliki risk rating 155 Pada metode Decision Tree model
